apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-app-credentials
  namespace: gowebapp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-store    # ✅ points to ASM store
    kind: ClusterSecretStore
  target:
    name: db-app-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: gowebapp/prod/database/app_cred
        property: username
    - secretKey: password
      remoteRef:
        key: gowebapp/prod/database/app_cred
        property: password
    - secretKey: database
      remoteRef:
        key: gowebapp/prod/database/app_cred
        property: database
    - secretKey: session_secret_key
      remoteRef:
        key: gowebapp/prod/database/app_cred
        property: session_secret_key