apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-endpoint
  namespace: gowebapp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store               # ✅ points to SSM store
    kind: ClusterSecretStore
  target:
    name: db-endpoint
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: /gowebapp/prod/database/host   # note the leading /
    - secretKey: port
      remoteRef:
        key: /gowebapp/prod/database/port