apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-root-credentials
  namespace: gowebapp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-store
  target:
    name: db-root-credentials  # Kubernetes secret name
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: rds!db-8405529e-f9c9-4cd8-b976-41e38acbd206
        property: username
    - secretKey: password
      remoteRef:
        key: rds!db-8405529e-f9c9-4cd8-b976-41e38acbd206
        property: password