# ExternalSecret for ROOT credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-root-credentials
  namespace: gowebapp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-gowebapp-store
    kind: ClusterSecretStore
  target:
    name: db-root-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: prod/do/database/mysql/root_cred
      property: username
  - secretKey: password
    remoteRef:
      key: prod/do/database/mysql/root_cred
      property: password